### ISSUE TITLE
RecordTimer.pyo is missing in /usr/lib/enigma2/python in fulan rootfs after image is built

### ISSUE THREAD

**Issue by lprot** [PLi-metas/pli-extras#10]

**Comment by MastaG** [comment]
Thanks for reporting my friend.
This means the python file doesn't compile.
I'll look into it next week.

**Comment by lprot** [comment]
Your welcome. Just for the record I just dropped that py from openpli's github and the image runs well.

**Comment by MastaG** [comment]
It has been fixed, by merging PLi's latest changes.
https://github.com/PLi-metas/enigma2-openpli-fulan/commit/385fb35264a93444fb497857f75cf732ce8c572c
Tested a fresh image on my spark7162 (GM Triplex) receiver, I can confirm the RecordTimer.pyo is present.

**Comment by lprot** [comment]
Thanks a lot. How can I compile an image for 7162? For 7111 I just used machine=spark what should I set for 7162?

**Comment by MastaG** [comment]
MACHINE=spark7162 :)
