### ISSUE TITLE
Welcome Persian Prince's 

### ISSUE THREAD

**Issue by atefganm** [PLi-metas/pli-extras#10]
atef@atefGanm ~/openpli-oe-core/pli-extras $ ./image.sh
-e 
-e Welcome to Persian Prince's image compile script!
-e Check README.md and enter a meta or a specific machine to compile.
-e Answers are in green:
-e 
-e AX - AZBox - BlackBox - BroadMedia - Ceryon - Clap
-e Cube - DAGS - Dinobot - Dreambox - EBox - Entwopia
-e Fulan - GB - HyperCube - INI - IXUSS - Linkdroid
-e MINIX - Octagon - Odin - Odroid - Protek - RaspberryPi
-e Tiviar - Tripledot - Uclan - WeTek - XCore - XT
-e ALL (Compiles all brands/models, As it requires huge free space it's not recommended)
-e Specific (I have a specific machine in mind)
-e 
-e Enter the meta name:
-e 
meta-dreambox
-e 
-e Now choose whether you want to compile Open Vision or the online feeds.
-e Answers are in red:
-e 
-e Vision
-e Feed
-e 
-e Enter image type:
-e 
Open Vision
-e 
-e First update everything, please wait ...

Open Vision by
https://github.com/orgs/PLi-metas/people

Each time you run this script all git repositories will get updated to their latest versions!

For extra RC support you need to add your STB files to https://github.com/PLi-metas/extra_rc_models

Already up-to-date.
Synchronizing submodule url for 'meta-ax'
Synchronizing submodule url for 'meta-azbox'
Synchronizing submodule url for 'meta-blackbox'
Synchronizing submodule url for 'meta-broadmedia'
Synchronizing submodule url for 'meta-ceryon'
Synchronizing submodule url for 'meta-clap'
Synchronizing submodule url for 'meta-cube'
Synchronizing submodule url for 'meta-dags'
Synchronizing submodule url for 'meta-dinobot'
Synchronizing submodule url for 'meta-dream'
Synchronizing submodule url for 'meta-ebox'
Synchronizing submodule url for 'meta-entwopia'
Synchronizing submodule url for 'meta-fulan'
Synchronizing submodule url for 'meta-gb'
Synchronizing submodule url for 'meta-hypercube'
Synchronizing submodule url for 'meta-ini'
Synchronizing submodule url for 'meta-ixuss'
Synchronizing submodule url for 'meta-linkdroid'
Synchronizing submodule url for 'meta-minix'
Synchronizing submodule url for 'meta-octagon'
Synchronizing submodule url for 'meta-odin'
Synchronizing submodule url for 'meta-odroid'
Synchronizing submodule url for 'meta-protek'
Synchronizing submodule url for 'meta-raspberrypi'
Synchronizing submodule url for 'meta-tiviar'
Synchronizing submodule url for 'meta-tripledot'
Synchronizing submodule url for 'meta-uclan'
Synchronizing submodule url for 'meta-wetek'
Synchronizing submodule url for 'meta-xcore'
Synchronizing submodule url for 'meta-xt'

Check for dm7020hdv2 required changes ...

No need to modify Makefile.
You can compile dm7020hdv2 image too.

Generating /home/atef/openpli-oe-core/build/conf/bblayers.conf
Updating Git repositories...
Already up-to-date.
Synchronizing submodule url for 'bitbake'
Synchronizing submodule url for 'meta-amiko'
Synchronizing submodule url for 'meta-axasuhd'
Synchronizing submodule url for 'meta-edision'
Synchronizing submodule url for 'meta-formuler'
Synchronizing submodule url for 'meta-gfutures'
Synchronizing submodule url for 'meta-gi'
Synchronizing submodule url for 'meta-gigablue'
Synchronizing submodule url for 'meta-miraclebox'
Synchronizing submodule url for 'meta-openembedded'
Synchronizing submodule url for 'meta-qt5'
Synchronizing submodule url for 'meta-qviart'
Synchronizing submodule url for 'meta-sab'
Synchronizing submodule url for 'meta-spycat'
Synchronizing submodule url for 'meta-vuplus'
Synchronizing submodule url for 'meta-xp'
Synchronizing submodule url for 'meta-xpeedc'
Synchronizing submodule url for 'meta-xsarius.pli5'
Synchronizing submodule url for 'meta-xtrend'
Synchronizing submodule url for 'meta-zgemma'
Synchronizing submodule url for 'openembedded-core'
The openpli OE is now up-to-date.
-e 
-e Updated.
-e 
-e Compiling meta-dreambox images, please wait ...
-e 
./image.sh: 40: [: Open: unexpected operator
./image.sh: 46: [: Open: unexpected operator
-e 
-e Done.
atef@atefGanm ~/openpli-oe-core/pli-extras $

**Comment by persianpros** [comment]
Look at the answers in colors, "Dreambox" is an answer not "meta-dreambox".
