### ISSUE TITLE
fulan image building is broken because grab.py of OpenWebIf is changed

### ISSUE THREAD

**Issue by lprot** [PLi-metas/pli-extras#11]

**Comment by lprot** [comment]
Current patch just won't apply

**Comment by MastaG** [comment]
I'll update the patch next week.. I'm very occupied with personal stuff lately. Apologies my friend.

**Comment by lprot** [comment]
Well, the grab is broken in OpenWebIf itself. I just replaced grab.pyo with the one from 1.3.2 develop of 11.04.2018 and it works as it is supposed to be. So the patch should be fixed after OpenWebIf grab code regression is fixed.

**Comment by MastaG** [comment]
Fixed with: https://github.com/PLi-metas/pli-extras/commit/0724e650af17d154364815a21a9bf6b326df104e

Screenshots work again on sh4 :)
