### ISSUE TITLE
Error enigma2.bb  spark

### ISSUE THREAD

**Issue by BarviX6** [PLi-metas/pli-extras#2]
WARNING: /home/barvix/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb: Exception during build_dependencies for PATH
WARNING: /home/barvix/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb: Error during finalise of /home/barvix/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb
ERROR: ExpansionError during parsing /home/barvix/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Unable to resolve 'master' in upstream git repository in git ls-remote output for github.com/PLi-metas/enigma2-openpli-fulan.git

Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by persianpros** [comment]
Update your pli-extras with "update.sh" and try again, there is no "enigma2-openpli-fulan.git" anymore.
