### ISSUE TITLE
Bootlogo won't show on spark

### ISSUE THREAD

**Issue by lprot** [PLi-metas/pli-extras#22]
If you replace the logo at /usr/share/bootlogo.mvi with OpenPLi Homebuild's logo of dm800 then it shows ok.

**Comment by lprot** [comment]
Well, I just replaced the logo at /usr/share/bootlogo.mvi with OpenPLi Homebuild logo of dm800 and it's showing ok. So the problem is that building not taking logo from OpenPLi sources.

**Comment by MastaG** [comment]
But by default the bootlogo.mvi (showing the Homebuild text) is the save for all images built using openpli-oe-core.
We don't modify it for a specific receiver.
I'll look into it.
