### ISSUE TITLE
audio.elf with DTS downmix support causes hang ups when playing some AAC media in mediaplayers on spark

### ISSUE THREAD

**Issue by lprot** [PLi-metas/pli-extras#25]
Currently spark target uses these firmwares:
https://github.com/Taapat/vuplus-fulan-openpli-oe-core/tree/master/meta-fulan/recipes-bsp/stslave-fw-dts/spark

With this firmware AAC media plays ok:
https://github.com/Taapat/vuplus-fulan-openpli-oe-core/tree/master/meta-fulan/recipes-bsp/stslave-fw-ac3/spark

Changing audio.elf is enough.

7162 is working with DTS fw without freezes.

**Comment by MastaG** [comment]
Fixed :)
Just run update.sh
