### ISSUE TITLE
On AC3 firmware decoding JPEGs with hardware acceleration corrupts the pictures (spark)

### ISSUE THREAD

**Issue by lprot** [PLi-metas/pli-extras#26]
![screenshot_20180712131527](https://user-images.githubusercontent.com/2608545/42632127-7f63bba6-85dc-11e8-9ca3-22ada8cf5e9c.jpg)

After some time enigma2 hangs and if you rerun it you gen get:

```
[ePicLoad] hardware decode picture... /tmp/419618.tmp
(mme_init_transformer): transformer initialisation failed: MME_DRIVER_ALREADY_INITIALIZED
[ePicLoad] hardware decode error
```

At this time all pictures are decoding ok, speed of decoding is not affected, so we need a way to switch off jpeg decoding acceleration off to be ok...

**Comment by MastaG** [comment]
are you sure it's caused by the non-dts drivers?
If yes, them I'll add an option to enable/disable hardware accelerated jpeg decoding somewhere in the gui.

**Comment by lprot** [comment]
100% with dts audio.elf it's decoding ok. But dts audio.elf causes AAC streams to hang. So disabling hw acceleration for ePicLoad is the cure. It's for 7111 only. 7162 is ok with DTS drivers as I reported before.

**Comment by MastaG** [comment]
I will do that.
In the mean time, try and rename /usr/lib/libmme_host.so to something else and restart e2
It's a pitty we have to deal with closed source firmware here.

**Comment by MastaG** [comment]
Btw, I remember I've also had the same problem on spark7162 in the past.
Perhaps this was caused from using the AC3 firmware as well.

**Comment by lprot** [comment]
Deleted libmme_host.so and it's working like a magic. Just in the log there are annoying messages about lib loading.

**Comment by lprot** [comment]
Interesting thing. After deleting  libmme_host.so, I returned DTS video.elf and audio.elf. And there are no more AAC hangups. So for 7111 you just need to disable JPEG hw decoding as it breaks AAC. You can revert to DTS drivers...

**Comment by lprot** [comment]
Update. Finally today I connected Sony DAV-X1 system to my 7111 based gm990 (spark reloaded) via SPDIF. 
The problem with DTS driver is - AC3 sound randomly fails to go to the SPDIF.

Replaced DTS video.elf+audio.elf to AC3 ones and SPDIF works properly.

So for 7111 bottom line is:
DTS drivers hang stb on AAC decoding because of acceleration of jpeg decoding. Spdif doesn't work properly. If you delete libmme_host.so, AAC is ok but SPDIF doesn't work properly.

With AC3 drivers - AAC and SPDIF are ok. But hardware jpeg decoding sometimes corrupts pictures. Deleting libmme_host.so solves jpeg corruption issue.

So if you need SPDIF ac3 drivers are better.
If you don't need SPDIF dts drivers can be useful.

**Comment by lprot** [comment]
Well. More tests and more results. My friend tested DTS driver on avatar2 stb that has triple tuner.
DTS driver is incompatible with dvb-t2 tiner. He replaced DTS drivers in /boot with AC3 drivers and it's ok.

So with DTS firmware on 7111:
1. AAC sound (if libmme_host.so is accelerating jpeg decoding) causes endless spinner.
2. SPDIF sound from time to time is silent.

On 7162:
1. If you use Dvb-t2 tuner  it goes GSOD

With AC3 firmware on 7111:
AAC is ok. SPDIF is ok. JPEG with hwaccel off are ok.

On 7162:
AAC is ok. SPDIF was not tested. JPEG with hwaccel were not tested.

So the bottom line is - you need to avoid DTS fw as it causes problems. Looks like that fw is for 7105 and is not suitable for 7111 and 7162...

**Comment by MastaG** [comment]
jpeg acceleration has now been disabled in meta-fulan :)
