### ISSUE TITLE
HDMICEC plugin fails to load on spark and spark7162

### ISSUE THREAD

**Issue by lprot** [PLi-metas/pli-extras#27]

**Comment by lprot** [comment]
[HdmiCEC.zip](https://github.com/PLi-metas/pli-extras/files/2188507/HdmiCEC.zip)
The one in attachment goes ok.

**Comment by MastaG** [comment]
I've just merged PLi's master branch of Enigma2, have you tried it since this monrning?

**Comment by lprot** [comment]
No. Will try later.

**Comment by MastaG** [comment]
Could you please try and build a fresh image after running pli-extras/update.sh
See: https://github.com/PLi-metas/meta-fulan/commit/77665778b887ae80c89b37a0e63e234ad17807ee

cec driver should always load during boot.

You should only enable it in the enigma2 gui.
