### ISSUE TITLE
ERROR: vision-enigma2-image-1.0-r0 do_rootfs

### ISSUE THREAD

**Issue by BarviX6** [PLi-metas/pli-extras#3]
ERROR: vision-enigma2-image-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /home/barvix/K/openpli-oe-core/build/tmp/work/spark-oe-linux/vision-enigma2-image/1.0-r0/temp/log.do_rootfs.4549
Collected errors:
 * check_data_file_clashes: Package iptraf wants to install file /home/barvix/K/openpli-oe-core/build/tmp/work/spark-oe-linux/vision-enigma2-image/1.0-r0/rootfs/var/log
	But that path is currently a directory
ma2-plugin-extensions-vlcplayer.

**Comment by Hains** [comment]
Sorry for delay..
https://github.com/PLi-metas/pli-extras/commit/26125fc3e9a017da7a1cd64ef2190199fd03ef91

Update pli-extras and everything should be fine now.
