### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by jenseneverest** [PLi-metas/pli-extras#3]
##Thanks for this everyone, greatly appreciated. I have found a few issues when trying to build for xpeedlx3

`Cloning into 'meta-dream'...
remote: Counting objects: 3786, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 3786 (delta 36), reused 55 (delta 19), pack-reused 3699
Receiving objects: 100% (3786/3786), 14.24 MiB | 4.75 MiB/s, done.
Resolving deltas: 100% (2182/2182), done.
Checking connectivity... done.
fatal: reference is not a tree: 3873b81c8c0d03ed54dccc16613360ad4dc11332`

when you bypass the above issue i then get a license issue with the meta .ini layer... best to fix it the right way rather than me hacking the crap out of it -- TIA

> jason@jason-X550MJ:~/openpli/openpli-oe-core/build$ MACHINE=xpeedlx3 bitbake openpli-enigma2-image
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
ERROR: ParseError at /home/jason/openpli/openpli-oe-core/pli-extras/meta-ini/recipes-bsp/ini-ethwol.bb:4: Could not include required file conf/license/license-close.inc

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by persianpros** [comment]
Ignore it and just build ;)
