### ISSUE TITLE
AC3 multi-channel audio volume is so low (spark)

### ISSUE THREAD

**Issue by Shadowman94** [PLi-metas/pli-extras#32]
If ac3 is streamed with 2ch( stereo ), volume is normal, but if the stream switched to multi-channel( 5.1) the sound is really quiet.

I installed alsamixer and can increase Post Mix and Primary volumes, but its not permanent and if Channel switch back to stereo mode, the audio is over amplifed :/ the default value of mixer is 12 and with 36 is good value for 5.1

![image](https://user-images.githubusercontent.com/652434/42739631-fea734b8-889a-11e8-9395-80d1f290db24.png)

**Comment by lprot** [comment]
What are the filesizes of /boot/audio.elf and /boot/video.elf and the model of your spark?

**Comment by Shadowman94** [comment]
I tried latest files (AC3) from git but volume level is same... but with that i see the osd is flicking some times o.O with orginal (DTS) files osd is good.

**Comment by Shadowman94** [comment]
Yep, osd is ok, but the sound volume is still low, i do some "hackfix" for that, manually set volumes in alsamixer and use automatic volume adjustment for set mpeg volume to 50% and AC3 to 100%, sounds good but this is not the best idea for production... :/

**Comment by lprot** [comment]
I guess ac3 fw with hw acceleration off is the best option for 7111 in any case. You can read about my experience here https://github.com/PLi-metas/pli-extras/issues/26

**Comment by MastaG** [comment]
I think it's I start practicing my Python skills a bit and create a small system plugin that's part of the enigma2-openpli-fulan branch with the following options:
- Choose memory split, e.g. more ram without PIP or less ram with PIP (only on SD-channels though)
- Enable / disable swap on zram
- Choose DTS or AC3 firmware
- Enable / disable JPEG hardware acceleration

That way people can set things the way they want it for themselves.

**Comment by kueken** [comment]
The difference in volume is also no mistake.
Of course you can intervene in the values. Unfortunately only leads to sound distortion.
It is cleverer to play stations preferably with Mpeg Stream.
This difference is also present in all boxes.

**Comment by persianpros** [comment]
I know https://github.com/PLi-metas/meta-fulan/blob/develop/recipes-bsp/linux/linux-fulan/linux-sh4-pcm_noise_fix_stm24_0217.patch is not related to this problem but if it helps we could apply it ...

**Comment by MastaG** [comment]
Apply it, then I'll try it out tonight

**Comment by kueken** [comment]
I think I remember that this leads to more 'crack-Sound' in the channel change.
The volume can be manipulated in the output values ​​as described above.
Then you have different levels, but this leads to unclean sound.
We could install the amixer and fix it.
This is how it is done in the neutrino.
For me, the difference in volume is not a mistake.

**Comment by persianpros** [comment]
@MastaG applied 👍

**Comment by persianpros** [comment]
I will close this if there was a problem with new kernel patches you could reopen it.
