### ISSUE TITLE
nbench-byte-2.2.3-r0 do_fetch ERROR

### ISSUE THREAD

**Issue by BarviX6** [PLi-metas/pli-extras#42]
WARNING: nbench-byte-2.2.3-r0 do_fetch: Failed to fetch URL http://www.tux.org/~mayer/linux/nbench-byte-2.2.3.tar.gz, attempting MIRRORS if available
ERROR: nbench-byte-2.2.3-r0 do_fetch: Fetcher failure for URL: 'http://www.tux.org/~mayer/linux/nbench-byte-2.2.3.tar.gz'. Unable to fetch URL from any source.
ERROR: nbench-byte-2.2.3-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/barvix/openpli-oe-core/build/tmp/work/sh4-oe-linux/nbench-byte/2.2.3-r0/temp/log.do_fetch.30762
ERROR: Task (/home/barvix/openpli-oe-core/meta-openembedded/meta-oe/recipes-benchmark/nbench-byte/nbench-byte_2.2.3.bb:do_fetch) failed with exit code '1'

**Comment by persianpros** [comment]
https://fossies.org/linux/misc/nbench-byte-2.2.3.tar.gz
