### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by MastaG** [PLi-metas/pli-extras#43]
@Hains @persianpros @moham96 
I see you've all been doing a tremendous job maintaining all these BSP-layers and keeping it as close to genuine PLi as possible.
However I see many people struggling trying to self-build an image.

Would it be an idea to lift this project to the next level?
e.g.
- Host a web-page with download links
- Host a public forum
- Create a PLi-Extras bootlogo (one that doesn't infringe copyright..)

What are your thoughts..I know we're all busy from time to time...
And of course webhosting and registering domain-names isn't free...

But running a nice community for this, would surely attract some more devs, testers, support etc..

**Comment by lprot** [comment]
domain like somname.tk is for free.
webhosting for the page is free on 000webhost.com (php and wordpress are included iirc)
links to compiled stuff can be on gdrive or mega
so no costs...

**Comment by persianpros** [comment]
@MastaG It's a great idea, I have a vbulletin 4 publishing suite original license which is far better than PLi's forum and I'm a great vbulletin forum manager myself so I can setup the forum but we need a good hosting with cpanel.

Having a good hosting for daily or weekly builds is the important thing ...

**Comment by persianpros** [comment]
Hains couldn't access git right now as he's on vacation but here is his message:

Regarding own website, hosting etc.
+1
I agree.

I'm on vacation for a few days. I can't login on github at the moment.
That's why i'm doing it this way.

**Comment by moham96** [comment]
Hi,
I myself can't commit to such a thing sadly, due to my currently limited free time (which will be more limited in a couple of weeks when my vacation ends).
I will try to help as much as I can but I can't give promises.

I don't really have a big problem with using Openpli forums for communicating, the only thing I really like is to have a webpage with download links.
If it's just a webpage we're looking for we can use [github pages](https://pages.github.com/) to have a project page with the links, the images can be hosted on drive,mega.nz...etc. Or we can just host them on GitHub using the [release function](https://help.github.com/articles/creating-releases/)( I do recommend this since GitHub has some great servers)

Regards

**Comment by kueken** [comment]
Some ideas on my part ...

It would be nice if Images had quite a few more things on board as a basis.
IpTV player and associated service app e.g.
SimpelGray Skin as an alternative I also liked it.

But more important would be an update from the build environment.
So Pyro last update and then update the certifacate up to date.
Mistakes through the old stuff are known.
In pli, unfortunately, referred to sumo, but there is nothing happening.
Pyro is the main branch and should also be updated.

Maybe you can see it here too.

greetings

**Comment by kueken** [comment]
https://github.com/openembedded/meta-openembedded/pull/64/files

Could that be interesting?

**Comment by Hains** [comment]
I would say, try it.
We have a working version of dvb-apps (from github atvcaptain).
The question is, which one is better?

**Comment by Hains** [comment]
Vision PLi sounds closed source.
OpenVisionPLi or so..

I have pictures of forest, city sky line from sea etc.
I'll collect them and see if there's something useful?
We can vote or change bootlogo weekly, monthly whatever.

**Comment by MastaG** [comment]
@Hains 
Great idea my friend, yes please do.
OpenVisionPLi seems a bit long though, perhaps just OpenVision?
"OpenVision - An attempt to bring PLi to a wider range of hardware"

If anybody else has input for names, just spit it out.

**Comment by MastaG** [comment]
@persianpros
I like the slogan: lets define enigma2 once more
Also I agree with @hains that it should at least have the word "Open" so people know it's fully opensource.
So something like:
OpenVision - Let's define Enigma2 once more

I like that one, but then it doesn't say that it derived from PLi..
But that's OK since we're going to change the bootlogo anyways, and who's knows even more customization to enigma2 and/or plugins in the future.

If anybody else has suggestions please let me know.
I'd like to register for a domain name and setup a public build-host and webserver so we can host images and a forum for discussions..

Because the way wer're now starting conversations in commit logs is a bit 'strange' :P

**Comment by moham96** [comment]
How about https://github.com/discourse/discourse for the forum? open source better than VBulletin?

**Comment by MastaG** [comment]
That sounds great, I can set this up easily.
However I guess we all need to agree on the name and slogan first ;)

**Comment by persianpros** [comment]
@MastaG any news my friend?

**Comment by MastaG** [comment]
yeah :)
check your PM on openpli.org :)

**Comment by persianpros** [comment]
Future discussions in PLi's forum please 👍
