### ISSUE TITLE
An error occurred while assembling spark71xxusbimg for Spark7111 / 7162 (meta-furan)

### ISSUE THREAD

**Issue by Ednaz** [PLi-metas/pli-extras#44]
Hi!
**spark 7111**
ERROR: openpli-enigma2-image-1.0-r0 do_image_spark71xxusbimg: Taskhash mismatch 19b800d8d95c6fc854010d54b006e24f versus ad842926d2d09fbd704672159ff18a20 for /media/myhome/openpli-oe-extras/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb.do_image_spark71xxusbimg
ERROR: Taskhash mismatch 19b800d8d95c6fc854010d54b006e24f versus ad842926d2d09fbd704672159ff18a20 for /media/myhome/openpli-oe-extras/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb.do_image_spark71xxusbimg
**spark7162**
ERROR: openpli-enigma2-image-1.0-r0 do_image_spark71xxusbimg: Taskhash mismatch 892155b70a01def58bd922e6d7f69fb6 versus 0713c6b1f92d5a3b025302c45e2f4959 for /media/myhome/openpli-oe-extras/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb.do_image_spark71xxusbimg
ERROR: Taskhash mismatch 892155b70a01def58bd922e6d7f69fb6 versus 0713c6b1f92d5a3b025302c45e2f4959 for /media/myhome/openpli-oe-extras/meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb.do_image_spark71xxusbimg

I made a record in reporefs.conf - there are no more errors when compiling

**Comment by persianpros** [comment]
Don't edit a recipe while you're compiling otherwise you'll get a "Taskhas missmatch" error, try again it would be ok.

**Comment by Ednaz** [comment]
OK. Thank you my friend! But I did not edit the recipes when I was compiling. I edit the recipes before or after the compilation. But the compilation already goes without errors.
