### ISSUE TITLE
cube compile problem

### ISSUE THREAD

**Issue by persianpros** [PLi-metas/pli-extras#45]
Hi my friends,

As I mentioned here: https://forums.openpli.org/topic/57419-howto-build-unofficial-pli-for-your-unsupported-receiver/?view=findpost&p=928919 I did fix all the builds and every model/brand is ok now but "cube" :(

I get an error regarding iw 4.9 and even with https://github.com/PLi-metas/pli-extras/blob/develop/recipes-connectivity/iw/iw_4.%25.bbappend it won't work, see:

ERROR: iw-4.9-r0 do_prepare_recipe_sysroot: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:extend_recipe_sysroot(d)
     0003:
File: '/home/persianprince/Desktop/PLi/openpli-oe-core/openembedded-core/meta/classes/staging.bbclass', lineno: 628, function: extend_recipe_sysroot
     0624:                    dest = newmanifest[l]
     0625:                    if l.endswith("/"):
     0626:                        staging_copydir(l, targetdir, dest, seendirs)
     0627:                        continue
 *** 0628:                    staging_copyfile(l, targetdir, dest, postinsts, seendirs)
     0629:
     0630:    for f in fixme:
     0631:        if f == '':
     0632:            staging_processfixme(fixme[f], recipesysroot, recipesysroot, recipesysrootnative, d)
File: '/home/persianprince/Desktop/PLi/openpli-oe-core/openembedded-core/meta/classes/staging.bbclass', lineno: 233, function: staging_copyfile
     0229:        os.symlink(linkto, dest)
     0230:        #bb.warn(c)
     0231:    else:
     0232:        try:
 *** 0233:            os.link(c, dest)
     0234:        except OSError as err:
     0235:            if err.errno == errno.EXDEV:
     0236:                bb.utils.copyfile(c, dest)
     0237:            else:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/persianprince/Desktop/PLi/openpli-oe-core/build/tmp/sysroots-components/armv7a-vfp/linux-libc-headers/usr/include/linux/net.h' -> '/home/persianprince/Desktop/PLi/openpli-oe-core/build/tmp/work/armv7a-vfp-oe-linux-gnueabi/iw/4.9-r0/recipe-sysroot/usr/include/linux/net.h'

ERROR: iw-4.9-r0 do_prepare_recipe_sysroot: Function failed: extend_recipe_sysroot
ERROR: Logfile of failure stored in: /home/persianprince/Desktop/PLi/openpli-oe-core/build/tmp/work/armv7a-vfp-oe-linux-gnueabi/iw/4.9-r0/temp/log.do_prepare_recipe_sysroot.28899
ERROR: Task (/home/persianprince/Desktop/PLi/openpli-oe-core/openembedded-core/meta/recipes-connectivity/iw/iw_4.9.bb:do_prepare_recipe_sysroot) failed with exit code '1'

**Comment by persianpros** [comment]
Yeah that's ok for me too, kernel is ok but iw no and no more after iw ...

**Comment by Hains** [comment]
OK image ready with iw..
I needed to add linux-libc-headers explicitly to DEPENDS quota 4.03 and iw.bb
Perhaps we need to update to quota 4.04, but i think not.
Also i needed to do some copy/paste work.
But perhaps with build from scratch no need for that.  

And add 
```
CXXFLAGS_append += " -std=c++11 -fPIC -fno-strict-aliasing "
```
to servicemp3.cpp to fix build with gcc 4.9.

**Comment by persianpros** [comment]
But if it's only for cube please add it to meta-cube 👍

**Comment by Hains** [comment]
I need more time to test work before i push to git.
I know the in and out's now.
When everything OK, i push to pli-extras/meta-cuba (i hope one of these days).

**Comment by persianpros** [comment]
Thanks a lot my friend so I close this :)
