### ISSUE TITLE
rt3070

### ISSUE THREAD

**Issue by kueken** [PLi-metas/pli-extras#46]
Hy

is there a reason for duplicate entry for rt3070?

https://github.com/PLi-metas/pli-extras/blob/develop/recipes-linux/linux-firmwares/firmware-rt3070.bb
https://github.com/PLi-metas/pli-extras/blob/develop/recipes-connectivity/realtek/rt3070_2.5.0.4.bb

**Comment by persianpros** [comment]
Hi kueken,

First one is only the firmware packages but second one is the driver itself.

**Comment by kueken** [comment]
The firmware is no longer needed with existing drivers, right? It causes an error when building, because of 'license closed'. Therefore the question if it can go away.
