### ISSUE TITLE
Recipes in pli-extras layer has no effect.

### ISSUE THREAD

**Issue by Hains** [PLi-metas/pli-extras#48]
Adding a recipe (no bbappend) to the pli-extras layer, does nothing at all.
For example

libvpx 1.6.1 in  recipes-multimedia/webm

But bitbake still downloading version 1.5.0. 
So the openpli-oe-core layer has a higher priority than pli-extras.

How can we solve this?
To add something like this (pseudo) to layer.conf?
```
BBFILE_COLLECTIONS += "pli-extras-layer"
BBFILE_PATTERN_pli-extras-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_pli-extras-layer = "8"

**Comment by persianpros** [comment]
Yes you can increase the priority but remember first remove the build folder and compile again if it's ok then we can use it because sometimes it breaks other thing :)

**Comment by Hains** [comment]
Yes it's triggers a completely rebuild. I build from scratch for test now.
Now it's bulding libvpx 1.6.1  instead of 1.5.0 :).
