### ISSUE TITLE
The sound disappears after switching channels to STx7111

### ISSUE THREAD

**Issue by Ednaz** [PLi-metas/pli-extras#56]
After the changes made in meta-fulan 20180918 after switching several channels, the sound disappears. Can recover by switching to another channel, or it may not recover. Previously, this was not.

**Comment by persianpros** [comment]
So we should revert https://github.com/PLi-metas/linux-sh4-2.6.32.71/commit/1da5a2d60c1b56b8d7d6daeb68efe5a8e558d7df

**Comment by Ednaz** [comment]
Compiled with patch. I'm testing ...
[linux-sh4-pcm_fix_stm24_0217.tar.gz](https://github.com/PLi-metas/pli-extras/files/2405268/linux-sh4-pcm_fix_stm24_0217.tar.gz)

**Comment by Ednaz** [comment]
@persianpros 
thank you friend
I tested it all day yesterday. I did not find the problem with the sound. Thank you.
