### ISSUE TITLE
[Dinobot4K] Remote Control Still No Response To Receiver

### ISSUE THREAD

**Issue by budiarno** [PLi-metas/pli-extras#7]
![img_20180515_065045](https://user-images.githubusercontent.com/15664372/40029161-327ae848-580d-11e8-894c-56cfe5edb788.jpg)

On first boot, I can see that the Remote Control picture still DMM. With the latest update, it should be Dinobot. Does it mean the rc_models is still dmm.xml?

**Comment by persianpros** [comment]
https://github.com/PLi-metas/extra_rc_models/blob/master/rc_models.cfg seems ok to me but maybe we can't detect your box correctly, could you tell us what's your "cat /proc/stb/info/boxtype"?

**Comment by budiarno** [comment]
Here it is the result:
```
root@u5:~# cat /proc/stb/info/boxtype
u5
root@u5:~# 
```

**Comment by persianpros** [comment]
Ok compile and test again :)
