### ISSUE TITLE
Please fix the errors

### ISSUE THREAD

**Issue by atefganm** [PLi-metas/pli-extras#9]
Please fix the errors
`atef@atefGanm ~/openpli-oe-core $ MACHINE=dm820 make image
Building image for dm820
Loading cache: 100% |##########################################################################################################################################################################################################| Time: 0:00:00
Loaded 3872 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################################################################| Time: 0:00:39
Parsing of 3306 .bb files complete (3021 cached, 285 parsed). 4157 targets, 969 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: multiple providers are available for runtime enigma2-plugin-extensions-openwebif (enigma2-plugin-extensions-openwebif, enigma2-plugin-extensions-openwebif-extras)
NOTE: consider defining a PREFERRED_RPROVIDER entry to match enigma2-plugin-extensions-openwebif

Build Configuration:
BB_VERSION        = "1.34.0"
BUILD_SYS         = "i686-linux"
NATIVELSBSTRING   = "linuxmint-18.3"
TARGET_SYS        = "mipsel-oe-linux"
MACHINE           = "dm820"
DISTRO            = "openpli"
DISTRO_VERSION    = "homebuild"
TUNE_FEATURES     = "o32 fpu-hard mips32"
TARGET_FPU        = ""
meta-oe           
meta-filesystems  
meta-multimedia   
meta-networking   
meta-python       
meta-webserver    = "HEAD:dfbdd28d206a74bf264c2f7ee0f7b3e5af587796"
meta              = "HEAD:93dd2f9f3edf0584f9e806c629611d645dd72dbf"
meta-openpli      = "develop:ebed9d7a0f21d83f7f73f3123b954a885b86bcb1"
meta-vuplus       = "HEAD:2c48f82d916314dfc41828415951b6cb2bf8e2e5"
meta-xsarius.pli5 = "HEAD:e4dbdeda56e48eac79d595273cb6dac3b71a6b88"
meta-qviart       = "HEAD:d6204dec4de3561647c4cefac209e3650a2a91d8"
meta-xp           = "HEAD:b37b33a53422b822a89bea2ca1696ab72320674a"
meta-xtrend       = "HEAD:7943a562ef70d0bd96872fb68d4fafecf4f2d664"
meta-formuler     = "HEAD:e1d33c48edb119dcc3163855b0b1af510912ef52"
meta-gfutures     = "HEAD:bbdf6cb1e0d6c49618258adeb4571247b2cc50f8"
meta-xpeedc       = "HEAD:f12908a5573de8a6a06ad9f75081846a590511c4"
meta-zgemma       = "HEAD:78c0f498e520d871770f50929242eccb2a42af0d"
meta-edision      = "HEAD:bde1cd0c5f53b0d3c65a8e8855296ad2b9addb7a"
meta-miraclebox   = "HEAD:99117bcc87c3bcf1885b631af915834e4d31bb9a"
meta-spycat       = "HEAD:a19f11bbcdcad969e9f6f8d2c30df0653427d4cb"
meta-gi           = "HEAD:01fd1e8256f53d40371e65514e13a53ef53e400d"
meta-sab          = "HEAD:92262feb14e4005c8096150daac7313e9cb3d85a"
meta-gigablue     = "HEAD:fb380cfc4f77850785dce4845101f1da4f67e314"
meta-amiko        = "HEAD:b6416ddfc6130265e0b3054d144b96b59fdf7a03"
meta-axasuhd      = "HEAD:dfc1465665f504fdc4d6fc9a401e630b04123211"
meta-local        = "develop:ebed9d7a0f21d83f7f73f3123b954a885b86bcb1"
meta-qt5          = "HEAD:c6aa602d0640040b470ee81de39726276ddc0ea3"
meta-ax           = "HEAD:c107e8c0d5d07b01a4b8d1d09e65cc08f07e1bb7"
meta-azbox        = "HEAD:78ff10e5e849f8e2d1e7ca2ed5cfd78058a5c94b"
meta-blackbox     = "HEAD:01b67040f5841084601bd927be15339ae9a2f390"
meta-broadmedia   = "HEAD:6da6693b349d7e0dbb0d713d1b17c874fad1ba2b"
meta-ceryon       = "HEAD:ce1568fec1e5dc2f696fc3707b959b76d020cbcf"
meta-clap         = "HEAD:6a8cbddf3f9115292d8483a34f4eb86860600ce7"
meta-cube         = "HEAD:42d3affd55a7ff32c88c1a9000befefaee5f41a3"
meta-dags         = "HEAD:bab30cfe6155c07bdea43f9a813a5ef292aa5c58"
meta-dinobot      = "HEAD:1f10e296686822e8014d929887c2e10ccba30eb7"
meta-dream        = "HEAD:881ef79e5cf307328a49c94d48aba4546777c791"
meta-ebox         = "HEAD:c967471abc29408917ccabb79bfa61e945c45725"
meta-entwopia     = "HEAD:74a27348bc03b2db4b982c44c25bf8bd9d5c3de6"
meta-fulan        = "HEAD:8f0f1011c35632fda05d40e2b04b7f572d31f38f"
meta-gb           = "HEAD:bbedc5793545760f0b189615320fab5aad8c48e6"
meta-hypercube    = "HEAD:b65609fb4db124ee09b023fbc459859de338769a"
meta-ini          = "HEAD:76ac9d85e4a394bb93a98000b11bde43fd5ec5a1"
meta-ixuss        = "HEAD:4c614c9174c87bbef4ec500f0f6c3b6b6ef66c94"
meta-linkdroid    = "HEAD:7c16365e366dc32261e45d84ff45451f7f8a4ff1"
meta-minix        = "HEAD:b7993e448b90c6112c0650bb7b7a1a0b1e73769d"
meta-octagon      = "HEAD:846d76e59ab6d54f99eeb56b79074bed89ba7864"
meta-odin         = "HEAD:6e7451a4077e9cf51666d574090367042efadf33"
meta-odroid       = "HEAD:5d4bbfb33629ed5f7f4c5201e2746f5ec585d423"
meta-protek       = "HEAD:d12bb1578a2b018baaef243121d8bd7dfdcf9273"
meta-raspberrypi  = "HEAD:f0735e6a13d45ab9a4ddd20ec082147ef8362137"
meta-tiviar       = "HEAD:f029cd6ccca4c7d2b73a24a1811dcaf8f753be7f"
meta-tripledot    = "HEAD:ff943ae92b31f258b82ac3f7e17cce4b122df292"
meta-uclan        = "HEAD:cbbfb69fdc5aff3014f5ecd5d471b0d638b87538"
meta-wetek        = "HEAD:83a443fd3dd865a37d0524293d0a2185ea1a3951"
meta-xcore        = "HEAD:f4d24b5adbf078e56857ace23fdb6e06d414cc8b"
meta-xt           = "HEAD:b1bf19eeb278497cd09f336205a5c0e44b424996"
pli-extras        = "develop:b641864fa49814af6a2e13713cf4e15bbc0a6eb0"

Initialising tasks: 100% |#####################################################################################################################################################################################################| Time: 0:00:18
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: enigma2-2.7+gitAUTOINC+ab3bbbd1ef-r0 do_patch: Command Error: 'quilt --quiltrc /home/atef/openpli-oe-core/build/tmp/work/dm820-oe-linux/enigma2/2.7+gitAUTOINC+ab3bbbd1ef-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch openvision.patch
patching file data/setup.xml
patching file lib/driver/hdmi_cec.cpp
patching file lib/python/Components/AVSwitch.py
patching file lib/python/Components/Network.py
Hunk #1 succeeded at 423 (offset 2 lines).
Hunk #2 succeeded at 495 (offset 2 lines).
patching file lib/python/Components/NimManager.py
Hunk #1 succeeded at 1574 (offset 6 lines).
Hunk #2 succeeded at 1582 (offset 6 lines).
Hunk #3 succeeded at 1590 (offset 6 lines).
patching file lib/python/Components/Sources/FrontendStatus.py
patching file lib/python/Components/UsageConfig.py
Hunk #4 FAILED at 80.
Hunk #8 succeeded at 281 with fuzz 2.
1 out of 8 hunks FAILED -- rejects in file lib/python/Components/UsageConfig.py
patching file lib/service/servicedvb.cpp
Patch openvision.patch does not apply (enforce with -f)
ERROR: enigma2-2.7+gitAUTOINC+ab3bbbd1ef-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/atef/openpli-oe-core/build/tmp/work/dm820-oe-linux/enigma2/2.7+gitAUTOINC+ab3bbbd1ef-r0/temp/log.do_patch.9878
ERROR: Task (/home/atef/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4790 tasks of which 4787 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_patch
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile:125: recipe for target 'image' failed
make: *** [image] Error 1
atef@atefGanm ~/openpli-oe-core $ 
`

**Comment by persianpros** [comment]
Remove your "build" directory and use "image.sh".
